FACE_DESCRIPTOR_PATH = "./Model/face_descriptors_final.npy"
MP_FILE_PATH = "./Model/mp_final.pkl"
SHAPE_PREDICTOR_PATH = "./Weights/shape_predictor_68_face_landmarks.dat"
FACE_RECOGNITION_MODEL_PATH = "./Weights/dlib_face_recognition_resnet_model_v1.dat"
G2_CAMERA_URL="rtsp://admin:sarwarR45@192.168.1.64:554/Streaming/Channels/101"
G1_CAMERA_URL="192.168.0.224:8080"